version: '3.1'

services:

  joueurs:
    build:
      context: ./MicroESport.Joueurs
    ports:
      - "7172:80"
    depends_on:
      - mongo
    # environment:
    #   MONGO_USERNAME: root
    #   MONGO_PASSWORD : AReallySecretPassword
    #   MONGO_HOST: mongo
    #   MONGO_PORT: 27017

  equipes:
    build:
      context: ./MicroESport.Equipes
    ports:
      - "7173:80"
    depends_on:
      - mongo
    # environment:
    #   MONGO_USERNAME: root
    #   MONGO_PASSWORD : AReallySecretPassword
    #   MONGO_HOST: mongo
    #   MONGO_PORT: 27017

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: AReallySecretPassword

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: AReallySecretPassword
      ME_CONFIG_MONGODB_URL: mongodb://root:AReallySecretPassword@mongo:27017/
